Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MOASC3/run_project.py", line 260, in <module>
    run_sentiment_classifier(multimodal_train_loader, multimodal_val_loader, multimodal_test_loader, params, device)
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MOASC3/run_project.py", line 227, in run_sentiment_classifier
    train(train_loader, validation_loader, test_loader, params, device)
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MOASC3/run_project.py", line 200, in train
    val_acc, val_loss, _, _ = evaluate(model, validation_loader)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MOASC3/run_project.py", line 138, in evaluate
    f1_macro += get_f1_macro(tp, fp, fn)
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'f1_macro' where it is not associated with a value
